name: master

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        exclude:
          - os: windows-latest
            python-version: 2.7.x
          - os: windows-latest
            python-version: 3.5.x
        os: [ 'macos-latest', 'ubuntu-latest', 'windows-latest' ]
        python-version: [ '2.7.x', '3.5.x', '3.6.x', '3.7.x' ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: jwsi/submodule-checkout@v1
      if: matrix.os == 'ubuntu-latest'
      with:
        ssh-key: '${{ secrets.TEST_DATA_SECRET }}'
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -e .
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        #flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        flake8 . --exit-zero  
    - name: Run unit tests with pytest
      run: |
        pytest -v -m 'not integration' tests/
#    - name: Run integration tests with pytest
#      if: matrix.os == 'ubuntu-latest'
#      run: |
#        INTEGRATION=1 pytest -v -m 'integration' tests/
